# ディレクトリパスの指定
ultra_simple_dir="/rplidar/sdk/output/Linux/Release"
output_dir="/rplidar/output/260219-0"

# 計測間隔(秒, 秒数によっては計測時間がずれる可能性があるので、本計測前にテスト計測で確認しておくこと)
interval=60

# 計測を自動終了するまでの時間(秒)
max_measurement_time=300